### ISSUE TITLE
[bug] Failed to load the classpath resource in flink application.

### ISSUE THREAD

**Issue by syhily** [keykey7/confij#48]
Flink override the default class loader. So the default [loading logic](https://github.com/keykey7/confij/blob/1b734262713200eac3d197208c9276068ef52267/confij-core/src/main/java/ch/kk7/confij/source/resource/ClasspathResource.java#L41) is not working in flink application.

**Comment by keykey7** [comment]
The [AnyResource](https://keykey7.github.io/confij/#anysource) might not work as it takes the default classloader.
However you can [explicitly](https://keykey7.github.io/confij/#_source_as_code) pass the class who's classloader should be used like so:
```
ConfijBuilder.of(ServerConfig.class)
    .loadFrom(ClasspathResource.ofName("/generic.properties").withClassloaderOf(getClass()))
    .build()
```
The `withClassloaderOf` tells it to look relative to that class and the `/` sais the file is at the classpath root (and not relative to class).
Let me know if that works in your setup. :crossed_fingers:

**Comment by syhily** [comment]
How about change it to `ClassLoader classLoader = Thread.currentThread().getContextClassLoader();`

**Comment by keykey7** [comment]
We can do that change as there are many other frameworks that change default classloaders and the currentThread is likely a good default. :+1:
